//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_In_game p_In_game;
        
        public static SteamVR_Input_ActionSet_In_game In_game
        {
            get
            {
                return SteamVR_Actions.p_In_game.GetCopy<SteamVR_Input_ActionSet_In_game>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_In_game = ((SteamVR_Input_ActionSet_In_game)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_In_game>("/actions/In_game")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.In_game};
        }
    }
}
