//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_In_game : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Skeleton LeftSkeleton
        {
            get
            {
                return SteamVR_Actions.in_game_LeftSkeleton;
            }
        }
        
        public virtual SteamVR_Action_Skeleton RightSkeleton
        {
            get
            {
                return SteamVR_Actions.in_game_RightSkeleton;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.in_game_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.in_game_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean Use
        {
            get
            {
                return SteamVR_Actions.in_game_Use;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.in_game_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touchpad
        {
            get
            {
                return SteamVR_Actions.in_game_Touchpad;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.in_game_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadClick
        {
            get
            {
                return SteamVR_Actions.in_game_TouchpadClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadPosition
        {
            get
            {
                return SteamVR_Actions.in_game_TouchpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.in_game_Haptic;
            }
        }
    }
}
